//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;

namespace BioinformaticsHelperLibrary.ExpasyScanProsite
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:expasy:scanprosite")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:expasy:scanprosite", IsNullable = false)]
    public partial class matchset
    {

        private matchsetMatch[] matchField;

        private string n_matchField;

        private string n_seqField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public matchsetMatch[] match
        {
            get { return this.matchField; }
            set { this.matchField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string n_match
        {
            get { return this.n_matchField; }
            set { this.n_matchField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string n_seq
        {
            get { return this.n_seqField; }
            set { this.n_seqField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:expasy:scanprosite")]
    public partial class matchsetMatch
    {

        private string sequence_acField;

        private string sequence_idField;

        private string sequence_dbField;

        private string startField;

        private string stopField;

        private string signature_acField;

        private string signature_idField;

        private string level_tagField;

        private string scoreField;

        private string levelField;

        /// <remarks/>
        public string sequence_ac
        {
            get { return this.sequence_acField; }
            set { this.sequence_acField = value; }
        }

        /// <remarks/>
        public string sequence_id
        {
            get { return this.sequence_idField; }
            set { this.sequence_idField = value; }
        }

        /// <remarks/>
        public string sequence_db
        {
            get { return this.sequence_dbField; }
            set { this.sequence_dbField = value; }
        }

        /// <remarks/>
        public string start
        {
            get { return this.startField; }
            set { this.startField = value; }
        }

        /// <remarks/>
        public string stop
        {
            get { return this.stopField; }
            set { this.stopField = value; }
        }

        /// <remarks/>
        public string signature_ac
        {
            get { return this.signature_acField; }
            set { this.signature_acField = value; }
        }

        /// <remarks/>
        public string signature_id
        {
            get { return this.signature_idField; }
            set { this.signature_idField = value; }
        }

        /// <remarks/>
        public string level_tag
        {
            get { return this.level_tagField; }
            set { this.level_tagField = value; }
        }

        /// <remarks/>
        public string score
        {
            get { return this.scoreField; }
            set { this.scoreField = value; }
        }

        /// <remarks/>
        public string level
        {
            get { return this.levelField; }
            set { this.levelField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:expasy:scanprosite")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:expasy:scanprosite", IsNullable = false)]
    public partial class NewDataSet
    {

        private matchset[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matchset")]
        public matchset[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    public static class Prosite
    {
        public static matchset XmlDeserialize()
        {
            XmlSerializer serializer = new XmlSerializer(typeof (matchset));
            matchset matchset;
            using (XmlReader xmlReader = XmlReader.Create("http://www.expasy.org/cgi-bin/prosite/PSScan.cgi?seq=ENTK_HUMAN&output=xml"))
            {
                matchset = (matchset) serializer.Deserialize(xmlReader);
            }

            return matchset;
        }
    }
}


