//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioinformaticsDissertationMSc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SequenceFileList {
            get {
                return ((string)(this["SequenceFileList"]));
            }
            set {
                this["SequenceFileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StructureFolderList {
            get {
                return ((string)(this["StructureFolderList"]));
            }
            set {
                this["StructureFolderList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterSequenceNonProteinAlphabet {
            get {
                return ((bool)(this["FilterSequenceNonProteinAlphabet"]));
            }
            set {
                this["FilterSequenceNonProteinAlphabet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterSequenceNonDimers {
            get {
                return ((bool)(this["FilterSequenceNonDimers"]));
            }
            set {
                this["FilterSequenceNonDimers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterSequenceDuplicates {
            get {
                return ((bool)(this["FilterSequenceDuplicates"]));
            }
            set {
                this["FilterSequenceDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterSequenceNonHomoDimers {
            get {
                return ((bool)(this["FilterSequenceNonHomoDimers"]));
            }
            set {
                this["FilterSequenceNonHomoDimers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterStructureMultipleModes {
            get {
                return ((bool)(this["FilterStructureMultipleModes"]));
            }
            set {
                this["FilterStructureMultipleModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterStructureNonDimers {
            get {
                return ((bool)(this["FilterStructureNonDimers"]));
            }
            set {
                this["FilterStructureNonDimers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterStructureNonInteracting {
            get {
                return ((bool)(this["FilterStructureNonInteracting"]));
            }
            set {
                this["FilterStructureNonInteracting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterStructureNonSymmetrical {
            get {
                return ((bool)(this["FilterStructureNonSymmetrical"]));
            }
            set {
                this["FilterStructureNonSymmetrical"] = value;
            }
        }
    }
}
